[Service]
Environment=QT_AUTO_SCREEN_SCALE_FACTOR=0
Environment=QT_ENABLE_HIGHDPI_SCALING=0
Environment=QT_SCALE_FACTOR_ROUNDING_POLICY=PassThrough
Environment=QT_SCALE_FACTOR=0.75
Environment=GDK_SCALE=1
Environment=GDK_DPI_SCALE=0.75
ExecStart=
ExecStart=/usr/bin/weston-lcd35
